import path from 'path';
import {
  MCPTool,
  Policy,
  Project,
  GeneratedFile,
  GeneratedFiles,
  TemplateContext,
} from '../types';
import { ensureDir, writeFile } from '../utils/fileUtils';

/**
 * MCP Generator Service
 * Generates MCP server code from templates
 */
class MCPGeneratorService {
  private generatedDir: string;

  constructor() {
    this.generatedDir = path.join(__dirname, '../../..', 'generated');
  }

  /**
   * Generate complete MCP server
   */
  async generateServer(
    project: Project,
    tools: MCPTool[],
    policy: Policy
  ): Promise<GeneratedFiles> {
    console.log(`[MCPGeneratorService] Generating MCP server for project: ${project.name}`);

    const projectDir = path.join(this.generatedDir, `mcp-server-${project.id}`);
    await ensureDir(projectDir);

    const context: TemplateContext = {
      projectName: project.name,
      projectVersion: '1.0.0',
      tools,
      endpoints: [], // Will be populated if needed
      policy,
      generatedAt: new Date().toISOString(),
    };

    const files: GeneratedFile[] = [];

    // Generate main server file
    files.push(await this.generateServerFile(context));

    // Generate tool files
    for (const tool of tools) {
      files.push(await this.generateToolFile(tool, context));
    }

    // Generate schemas file
    files.push(await this.generateSchemasFile(tools, context));

    // Generate policy file
    files.push(await this.generatePolicyFile(policy, context));

    // Generate package.json
    files.push(await this.generatePackageJson(context));

    // Generate tsconfig.json
    files.push(await this.generateTsConfig(context));

    // Generate README
    files.push(await this.generateReadme(context));

    // Generate test files
    for (const tool of tools) {
      files.push(await this.generateTestFile(tool, context));
    }

    // Write all files to disk
    for (const file of files) {
      const filePath = path.join(projectDir, file.path);
      await ensureDir(path.dirname(filePath));
      await writeFile(filePath, file.content);
    }

    // Save metadata file
    const metaPath = path.join(projectDir, '.bobforge-meta.json');
    await writeFile(
      metaPath,
      JSON.stringify(
        {
          projectId: project.id,
          projectName: project.name,
          generatedAt: context.generatedAt,
          toolCount: tools.length,
        },
        null,
        2
      )
    );

    const structure = this.generateFileStructure(files);

    console.log(`[MCPGeneratorService] Generated ${files.length} files`);

    return {
      files,
      structure,
      projectId: project.id,
      generatedAt: context.generatedAt,
    };
  }

  /**
   * Generate main server file
   */
  private async generateServerFile(context: TemplateContext): Promise<GeneratedFile> {
    const toolImports = context.tools
      .map((tool) => `import { ${tool.name}, ${tool.name}Schema } from './tools/${tool.name}.js';`)
      .join('\n');

    const toolCases = context.tools
      .map(
        (tool) => `    case '${tool.name}':
      return await ${tool.name}(args as any);`
      )
      .join('\n');

    const toolsList = context.tools
      .map(
        (tool) => `    {
      name: '${tool.name}',
      description: '${tool.description}',
      inputSchema: ${tool.name}Schema
    }`
      )
      .join(',\n');

    const content = `import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

// Import tools
${toolImports}

/**
 * ${context.projectName} MCP Server
 * Generated by BobForge on ${context.generatedAt}
 */
const server = new Server(
  {
    name: '${context.projectName.toLowerCase().replace(/\s+/g, '-')}',
    version: '${context.projectVersion}',
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// List available tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
${toolsList}
    ],
  };
});

// Handle tool execution
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
${toolCases}
      default:
        throw new Error(\`Unknown tool: \${name}\`);
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    return {
      content: [
        {
          type: 'text',
          text: \`Error executing tool \${name}: \${errorMessage}\`,
        },
      ],
      isError: true,
    };
  }
});

// Start server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.log('${context.projectName} MCP Server running');
}

main().catch((error) => {
  console.error('Server error:', error);
  process.exit(1);
});
`;

    return {
      path: 'src/index.ts',
      content,
      type: 'typescript',
    };
  }

  /**
   * Generate individual tool file
   */
  private async generateToolFile(tool: MCPTool, context: TemplateContext): Promise<GeneratedFile> {
    const schemaName = `${tool.name}Schema`;

    const content = `import { z } from 'zod';

/**
 * ${tool.description}
 * Risk Level: ${tool.riskLevel}
 * Approval Required: ${tool.approvalRequired ? 'Yes' : 'No'}
 */

// Input schema
export const ${schemaName} = z.object({
${this.generateZodSchemaFields(tool.inputSchema)}
});

export type ${tool.name}Input = z.infer<typeof ${schemaName}>;

/**
 * Execute ${tool.name}
 */
export async function ${tool.name}(args: ${tool.name}Input) {
  // Validate input
  const validated = ${schemaName}.parse(args);

  // TODO: Implement actual API call
  // For now, return mock response
  const mockResponse = {
    tool: '${tool.name}',
    input: validated,
    result: 'Mock response - replace with actual API call',
    timestamp: new Date().toISOString(),
  };

  return {
    content: [
      {
        type: 'text',
        text: JSON.stringify(mockResponse, null, 2),
      },
    ],
  };
}
`;

    return {
      path: `src/tools/${tool.name}.ts`,
      content,
      type: 'typescript',
    };
  }

  /**
   * Generate Zod schema fields from input schema
   */
  private generateZodSchemaFields(inputSchema: any): string {
    if (!inputSchema || !inputSchema.properties) {
      return '  // No input parameters';
    }

    const fields: string[] = [];
    const required = inputSchema.required || [];

    for (const [key, value] of Object.entries(inputSchema.properties)) {
      const prop = value as any;
      const isRequired = required.includes(key);
      const zodType = this.mapToZodType(prop.type);
      const optional = isRequired ? '' : '.optional()';
      const description = prop.description ? `.describe('${prop.description}')` : '';

      fields.push(`  ${key}: z.${zodType}()${description}${optional},`);
    }

    return fields.join('\n');
  }

  /**
   * Map type to Zod type
   */
  private mapToZodType(type: string): string {
    switch (type) {
      case 'string':
        return 'string';
      case 'number':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'array':
        return 'array';
      case 'object':
        return 'object';
      default:
        return 'string';
    }
  }

  /**
   * Generate schemas index file
   */
  private async generateSchemasFile(tools: MCPTool[], context: TemplateContext): Promise<GeneratedFile> {
    const exports = tools.map((tool) => `export { ${tool.name}Schema } from '../tools/${tool.name}';`).join('\n');

    const content = `/**
 * Schema exports for ${context.projectName}
 * Generated by BobForge
 */

${exports}
`;

    return {
      path: 'src/schemas/index.ts',
      content,
      type: 'typescript',
    };
  }

  /**
   * Generate policy file
   */
  private async generatePolicyFile(policy: Policy, context: TemplateContext): Promise<GeneratedFile> {
    const content = JSON.stringify(policy, null, 2);

    return {
      path: 'policy.json',
      content,
      type: 'json',
    };
  }

  /**
   * Generate package.json
   */
  private async generatePackageJson(context: TemplateContext): Promise<GeneratedFile> {
    const packageJson = {
      name: context.projectName.toLowerCase().replace(/\s+/g, '-'),
      version: context.projectVersion,
      description: `MCP server for ${context.projectName}`,
      type: 'module',
      main: 'dist/index.js',
      scripts: {
        build: 'tsc',
        start: 'node dist/index.js',
        dev: 'tsx watch src/index.ts',
        test: 'jest',
      },
      dependencies: {
        '@modelcontextprotocol/sdk': '^0.5.0',
        zod: '^3.22.4',
      },
      devDependencies: {
        '@types/node': '^20.10.0',
        typescript: '^5.3.3',
        tsx: '^4.7.0',
        jest: '^29.7.0',
        '@types/jest': '^29.5.11',
      },
    };

    return {
      path: 'package.json',
      content: JSON.stringify(packageJson, null, 2),
      type: 'json',
    };
  }

  /**
   * Generate tsconfig.json
   */
  private async generateTsConfig(context: TemplateContext): Promise<GeneratedFile> {
    const tsConfig = {
      compilerOptions: {
        target: 'ES2022',
        module: 'ES2022',
        moduleResolution: 'node',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist'],
    };

    return {
      path: 'tsconfig.json',
      content: JSON.stringify(tsConfig, null, 2),
      type: 'json',
    };
  }

  /**
   * Generate README
   */
  private async generateReadme(context: TemplateContext): Promise<GeneratedFile> {
    const toolsList = context.tools
      .map(
        (tool) =>
          `- **${tool.name}**: ${tool.description} (Risk: ${tool.riskLevel}${
            tool.approvalRequired ? ', Approval Required' : ''
          })`
      )
      .join('\n');

    const content = `# ${context.projectName} MCP Server

Generated by BobForge on ${new Date(context.generatedAt).toLocaleString()}

## Overview

This MCP server provides ${context.tools.length} tools for interacting with ${context.projectName}.

## Available Tools

${toolsList}

## Installation

\`\`\`bash
npm install
\`\`\`

## Build

\`\`\`bash
npm run build
\`\`\`

## Run

\`\`\`bash
npm start
\`\`\`

## Development

\`\`\`bash
npm run dev
\`\`\`

## Testing

\`\`\`bash
npm test
\`\`\`

## Risk Policy

This server implements enterprise-grade safety controls:

- **LOW risk**: Execute immediately
- **MEDIUM risk**: Execute with logging
- **HIGH risk**: Requires approval
- **CRITICAL risk**: Requires approval + additional verification

See \`policy.json\` for detailed risk rules.

## Integration

To use this MCP server with an AI agent:

1. Build the server: \`npm run build\`
2. Configure your AI agent to use this MCP server
3. The agent can now call the available tools

## Generated by BobForge

This MCP server was automatically generated by BobForge, a tool that converts API documentation into secure, tested, and agent-ready MCP servers.

Learn more: https://github.com/your-org/bobforge
`;

    return {
      path: 'README.md',
      content,
      type: 'markdown',
    };
  }

  /**
   * Generate test file for a tool
   */
  private async generateTestFile(tool: MCPTool, context: TemplateContext): Promise<GeneratedFile> {
    const content = `import { ${tool.name}, ${tool.name}Schema } from '../src/tools/${tool.name}';

describe('${tool.name}', () => {
  test('should execute with valid input', async () => {
    const input = {
      // TODO: Add valid test input
    };

    const result = await ${tool.name}(input);
    
    expect(result).toBeDefined();
    expect(result.content).toBeDefined();
    expect(result.content[0].type).toBe('text');
  });

  test('should validate input schema', () => {
    const validInput = {
      // TODO: Add valid input
    };

    expect(() => ${tool.name}Schema.parse(validInput)).not.toThrow();
  });

  test('should reject invalid input', () => {
    const invalidInput = {
      // TODO: Add invalid input
    };

    expect(() => ${tool.name}Schema.parse(invalidInput)).toThrow();
  });

  ${
    tool.approvalRequired
      ? `test('should require approval for high-risk operation', async () => {
    // This tool requires approval before execution
    // In production, check approval status before executing
    expect(true).toBe(true); // Placeholder
  });`
      : ''
  }
});
`;

    return {
      path: `tests/${tool.name}.test.ts`,
      content,
      type: 'typescript',
    };
  }

  /**
   * Generate file structure array
   */
  private generateFileStructure(files: GeneratedFile[]): string[] {
    return files.map((f) => f.path).sort();
  }

  /**
   * Get generated files for a project
   */
  async getGeneratedFiles(projectId: string): Promise<GeneratedFiles | null> {
    const fs = require('fs').promises;
    const projectDir = path.join(this.generatedDir, `mcp-server-${projectId}`);
    
    try {
      // Check if directory exists
      await fs.access(projectDir);
      
      // Read all files recursively
      const files: GeneratedFile[] = [];
      
      async function readDir(dir: string, baseDir: string) {
        const entries = await fs.readdir(dir, { withFileTypes: true });
        
        for (const entry of entries) {
          const fullPath = path.join(dir, entry.name);
          const relativePath = path.relative(baseDir, fullPath);
          
          if (entry.isDirectory()) {
            await readDir(fullPath, baseDir);
          } else {
            const content = await fs.readFile(fullPath, 'utf-8');
            const ext = path.extname(entry.name);
            let type: 'typescript' | 'json' | 'markdown' | 'text' = 'text';
            
            if (ext === '.ts') type = 'typescript';
            else if (ext === '.json') type = 'json';
            else if (ext === '.md') type = 'markdown';
            
            files.push({
              path: relativePath.replace(/\\/g, '/'),
              content,
              type,
            });
          }
        }
      }
      
      await readDir(projectDir, projectDir);
      
      const structure = this.generateFileStructure(files);
      
      // Try to read metadata file if it exists
      let generatedAt = new Date().toISOString();
      try {
        const metaPath = path.join(projectDir, '.bobforge-meta.json');
        const metaContent = await fs.readFile(metaPath, 'utf-8');
        const meta = JSON.parse(metaContent);
        generatedAt = meta.generatedAt;
      } catch {
        // No metadata file, use current time
      }
      
      return {
        files,
        structure,
        projectId,
        generatedAt,
      };
    } catch (error) {
      // Directory doesn't exist or can't be read
      return null;
    }
  }
}

// Export singleton instance
export const mcpGeneratorService = new MCPGeneratorService();

// Made with Bob
